'use client';
import { useEffect, useState } from 'react';

export default function SocialProfilePage() {
  const [profile, setProfile] = useState<any>(null); const [status, setStatus] = useState('');
  useEffect(() => { fetch('/api/social/profile').then((r) => r.json()).then((d) => setProfile(d.profile)); }, []);
  async function save(e: any) { e.preventDefault(); setStatus('Saving...'); const fd = new FormData(e.currentTarget); const body = { displayName: fd.get('displayName'), hostCity: fd.get('hostCity'), hostCountry: fd.get('hostCountry'), studyArea: fd.get('studyArea'), bio: fd.get('bio'), languages: String(fd.get('languages') || '').split(',').map((s) => s.trim()).filter(Boolean), interests: String(fd.get('interests') || '').split(',').map((s) => s.trim()).filter(Boolean) }; const res = await fetch('/api/social/profile', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await res.json(); setProfile(data); setStatus(res.ok ? 'Profile updated.' : 'Could not update profile.'); }
  if (!profile) return <p>Loading social profile...</p>;
  return <div className='space-y-4'><h1 className='text-2xl font-semibold'>My social profile</h1><p className='text-sm text-slate-600'>This profile is for Erasmus social support and discovery. Official mobility processing stays in the institutional area.</p><form className='space-y-3 rounded-xl border p-4' onSubmit={save}><input name='displayName' defaultValue={profile.displayName || ''} placeholder='Display name' className='w-full rounded border px-3 py-2' /><input name='hostCity' defaultValue={profile.hostCity || ''} placeholder='Host city' className='w-full rounded border px-3 py-2' /><input name='hostCountry' defaultValue={profile.hostCountry || ''} placeholder='Host country' className='w-full rounded border px-3 py-2' /><input name='studyArea' defaultValue={profile.studyArea || ''} placeholder='Study area' className='w-full rounded border px-3 py-2' /><input name='languages' defaultValue={(profile.languages || []).join(', ')} placeholder='Languages (comma separated)' className='w-full rounded border px-3 py-2' /><input name='interests' defaultValue={(profile.interests || []).join(', ')} placeholder='Interests (comma separated)' className='w-full rounded border px-3 py-2' /><textarea name='bio' defaultValue={profile.bio || ''} placeholder='Short bio' className='w-full rounded border px-3 py-2' /><button className='rounded bg-slate-900 px-4 py-2 text-white'>Save profile</button></form><p className='text-sm'>{status}</p></div>;
}
